thp/psmoveapi

- bindings/unity/src/UniMoveController.cs
(duplicated in https://github.com/CopenhagenGameCollective/UniMove/pull/7 as well)
if you have very high frame rates (for example, if you comment out the psmove_tracker_updateimage), the down/up/pressed states of buttons would not be reliable.
> fixing button flickering if the message queue was empty

- .gitignore
i ignore `build*` (not `build/*` or `build`) on purpose:
`build*` will ignore `build`, but also `build32` and `build64`, and even `build-bananas`. The last one is not really important, but i use the two in the middle in my build script.
> ignoring build directory from git

- examples/c/test_capture_performance.c
I was curious about the framerate and the shortest possible delay between framegrabs. I used your capture_performance-tool and altered it slightly.
It now adds two things to the previous state: start time (in ms since start of psmoveapi) and time between two iterations.
In the end it will print a summary to `STDOUT`.
> capture performance now records start and delta-t for each frame

- examples/c/test_extension.c
- include/psmove.h
- src/psmove.c
This adds a library function for sending arbitrary data to a connected extension device. It includes an example application that makes the Racing Wheel's two motors rumble.
> Send data to extension device

- examples/c/test_extension.c
- include/psmove.h
- src/psmove.c
- src/psmove_calibration.c
Since Google Code will shut down, I decided to transfer the documentation I maintained as part of the moveonpc project to GitHub. The wiki can now be found at:
https://github.com/nitsch/moveonpc/wiki
> Fix wiki links to point to new location

- src/platform/psmove_winsupport.c
- src/platform/psmove_winsupport.h
MinGW contains Windows headers files with lower-case filenames only. When cross-compiling on Linux, some of these would not be found due to case-sensitivity. This fix converts the names to lower case in the #include directives.
> Fix Windows include filenames

- src/platform/psmove_winsupport.c
- src/psmove.c
Can someone (@nitsch) please test this in Windows 7? Or in other Windows 8 @betonme ?
All of the relevant changes are in ifdef tags so they should only affect Windows.
With these changes the controller works well for me in Windows 8.1. I can use the psmovepair utility, magnetometer_calibration, and test_calibration (USB connection required for the first time).
> Separation of feature reports across 3 devices in Win 8.1

- CMakeLists.txt
This adds the OpenCV headers to installed headers when using a local OpenCV. Using the PSMoveTracker requires the presence of these headers to write a frame to the OpenCV window.
> install OpenCV headers when using local OpenCV

- src/utils/moved.c
moved.c is missing initialisation code for the wsa library on windows and will always throw an assertion when started.
This commit adds the WSAStartup call ( copied from src/daemon/moved_client.c, where it is already present )
> properly initialise wsa networking in moved.c on windows

- examples/c/test_tracker.c
- src/tracker/platform/camera_control_macosx.c
- src/tracker/platform/camera_control_win32.c
- src/tracker/psmove_tracker.c
This replaces PR #152 
-tracker fails gracefully when PS3EYE specified at compile time but not plugged in.
-exposure and gain parameters passed through to PS3EYE when using PS3EYEDriver. This greatly improves the performance of the tracker in well-lit environments.
> Ps3eye fixes in Windows and OSX.

- README.ubuntu
Though this information exists in contrib/README, there is no obvious path from reading the root README then README.ubuntu to indicate that this step is necessary.
> Modified README.ubuntu to give directions on copying the udev rules

- src/tracker/platform/camera_control_win32.c
so cc->eye will only be used when configured
> Added #ifdef CAMERA_CONTROL_USE_PS3EYE_DRIVER

- src/psmove.c
The device serial can be an empty string. Make sure to properly check this in order to not screw up the connection process for controllers that are attached via USB.
> Fix connection of USB controllers

- docs/README.win32_mingw64
- src/platform/psmove_winsupport.c
- src/platform/psmove_winsupport.h
- src/psmove.c
This adds setting the device's "VirtuallyCabled" property in the registry to the psmovepair utility. @betonme @cboulay  and other Windows 8 users: please test!
> Make Bluetooth pairing/connecting work in Windows 8

- examples/c/psmove_examples_opengl.h
- src/tracker/camera_control.c
Fixed Window build issue with latest version of PSMoveAPI and fixed crash when using the camera in non-640x480 mode.
> Windows fixes

- contrib/build_scripts/msvc/build_msvc_common.bat
- contrib/build_scripts/osx/build-osx-snapshot
- docs/README.win64_msvc
- external/msvc-support/unistd.h
- src/math/psmove_math.h
- src/math/psmove_quaternion.cpp
- src/tracker/CMakeLists.txt
- src/tracker/psmove_tracker.c
- src/tracker/tracker_helpers.h
I've updated the Windows build to also use OpenCV 3.1 instead of the older 2.4.11 so that all platforms now use the same OpenCV version. I tried doing this a while ago as part of my VS2013 support work (https://github.com/thp/psmoveapi/pull/190), but back then I was seeing a crash when `cvGetSize` was called during `psmove_tracker_blinking_calibration`.
That crash is still there, but I've spent some time investigating the crash and it turns out it's caused by a bug in OpenCV that causes incorrect code to be generated when `cvGetSize` is called from a C source file under MSVC (it works fine when called from C++/other compilers).
I've opened a bug on OpenCV's tracker (https://github.com/Itseez/opencv/issues/6221) detailing my findings, but in the meantime, since `psmove_tracker.c` is the …
> OpenCV 3.1 + MingW build fix

- include/psmove_tracker.h
- src/tracker/psmove_tracker.c
Those strings are probably not going to change, and if they do,
we should properly manage the memory of the strings (strdup()
when set, and free() when closing), which makes memory management
of the settings unnecessarily complicated. Plus, it was all relative
to the PS Move API configuration directory, anyway.
> Remove intrinsics.xml/distortion.xml from settings

- src/tracker/CMakeLists.txt
- src/tracker/camera_control.c
- src/tracker/camera_control_private.h
- src/tracker/platform/camera_control_win32.c
- src/tracker/psmove_tracker.c
The CL Eye Driver is still supported on Windows, but
the specific CL Eye SDK is not used anymore here.
> Remove support for the CL Eye SDK

- README
- contrib/build_scripts/msvc/build_msvc_common.bat
- external/README
The Madgwick AHRS algorithm is still used, but implemented
freshly for PS Move API in src/psmove_orientation.cpp these
days, so remove the remaining references in the README files
and in the MSVC build script (the option doesn't exist anymore).
> Remove references to old Madgwick AHRS implementation

- src/platform/psmove_linuxsupport.c
Maybe using a more generic method to find out whether the system is currently booted with systemd would be better (I'm sure e.g. gentoo has systemd too).
For example
```c
if (system("init --version | grep systemd > /dev/null 2> /dev/null") == 0) {
```
seems to work but there is probably a better way.
> add Archlinux to Systemd distributions

- src/CMakeLists.txt
This way, multiple build configuations (with different `psmove_config.h`) can be built in subdirectories of the same PS Move API source tree without the latest build overwriting the `psmove_config.h` changes of other builds.
> Do not clobber the source tree with psmove_config.h

- include/psmove.h
- src/platform/psmove_linuxsupport.c
- src/platform/psmove_linuxsupport.h
- src/platform/psmove_port_linux.c
- src/platform/psmove_port_osx.c
- src/platform/psmove_port_windows.c
- src/psmove.c
- src/utils/CMakeLists.txt
- src/utils/psmoveregister.c
This allows adding the correct BlueZ entries on a host for a given controller even if the controller has been paired on another host.
> Separate registering controllers from pairing

- src/platform/psmove_port_osx.m
Fixes a compiler warning and cleans up the indirection added by merging the platform-specific code.
> macOS: macosx_blued_register_psmove -> psmove_port_register_psmove

- contrib/convert-include-guards.py
- include/psmove.h
- include/psmove_config.h.in
- include/psmove_fusion.h
- include/psmove_tracker.h
- src/daemon/moved_client.h
- src/daemon/moved_monitor.h
- src/daemon/psmove_moved_protocol.h
- src/math/psmove_math.h
- src/math/psmove_vector.h
- src/psmove_calibration.h
- src/psmove_orientation.h
- src/psmove_port.h
- src/psmove_private.h
- src/psmove_sockets.h
- src/tracker/camera_control.h
- src/tracker/camera_control_private.h
- src/tracker/platform/psmove_linuxsupport.h
- src/tracker/platform/psmove_osxsupport.h
- src/tracker/tracker_helpers.h
Automatically converted using:
zsh% python3 contrib/convert-include-guards.py include/* src/**/*.h
Manually converted `src/tracker/camera_control_private.h`, which had broken include guards (trailing data after `#endif`).
> Convert include guards to #pragma once

- src/tracker/psmove_fusion.cpp
Ideally we would convert this to a single calculation and remove the binary search, but this is just a quick fix.
> Fix size search for psmove_fusion_get_position()

- src/platform/psmove_port_osx.m
Do not log / start up Bluetooth if it's already running.
Normalize Bluetooth address string returned by the get Bluetooth address function.
> Improve macOS Bluetooth pairing

- contrib/build_scripts/osx/build-osx-snapshot
Linking step fails when OpenCV is built against GStreamer on macOS (`brew install gstreamer`).
> Do not build against GStreamer on macOS

- cmake/common.cmake
- src/CMakeLists.txt
There should preferably be only one spot where we configure the C++ and C language standard version.
Reference: https://crascit.com/2015/03/28/enabling-cxx11-in-cmake/
> Centralize choosing of C++ standard, support CMake < 3.1

- src/psmove_calibration.c
We must not `return 0;` if the system-wide file was successfully loaded. Also, since proper operation of most of the API depends on the calibration data being available, warn if it is not available.
> Fix system-wide calibration loading; warn if missing

- src/CMakeLists.txt
psmove_config.h needs to be put into CMAKE_BINARY_DIR before PSMOVEAPI_HEADERS is populated or it will not be included in the variable and will not be installed
> Fix installation of psmove_config.h file

- docs/build.rst
Everyone should know how to clone the source repo or get the source tarball.
> Do not include cloning in build instructions (Fixes #286)

- .gitmodules
Until it's fixed in upstream (https://github.com/signal11/hidapi/pull/219), let's use hidapi patched with cbuolay's fixes applied. I've verified that this makes psmoveapi work on Windows 10.
Fixes: https://github.com/thp/psmoveapi/issues/214
> hidapi: Use Windows 10 fixes by cboulay (Fixes #214)

- scripts/build_package.sh
Right now only for the MSVC builds, since those are most likely used for linking against when building something with MSVC (the `.lib` stubs are not yet included with the MinGW builds).
> Include linker stubs for MSVC builds (Fixes #210)

- bindings/CMakeLists.txt
- docs/build.rst
- examples/python/always.py
- examples/python/beat.py
- examples/python/color_fade_multiple.py
- examples/python/cops.py
- examples/python/ep_whack.py
- examples/python/magnetometer_proximity_ngj.py
- examples/python/nose_tests_runner.py
- examples/python/pair.py
- examples/python/psmove_test.py
- examples/python/red_green.py
- examples/python/red_green_multiple.py
- examples/python/test_calibration.py
- examples/python/test_distance.py
- examples/python/test_exposure.py
- examples/python/test_fusion_pygame.py
- examples/python/test_tracker.py
- examples/python/tracker_image_pygame.py
This should fix a couple of problems people were having with Python bindings (see #328 and #335 for example). Also some documentation that we can refer to (and hopefully build upon).
> Improve Python build, examples, and docs

- CMakeLists.txt
- bindings/CMakeLists.txt
- bindings/copy_java.bat
- scripts/build_package.sh
Build was broken on Windows using Visual Studio.
> Fix Windows build of Java and Processing bindings

- scripts/install_dependencies.sh
Install `python` via Homebrew and use `pip2` for installing Sphinx.
> Install Python to macOS, so 'pip' works

- scripts/macos/build-macos
- scripts/mingw64/cross-compile
- scripts/visualc/build_msvc.bat
> Use OpenCV 2.4 (Fixes #336)

- scripts/macos/build-macos
I've modified the MacOS build script to allow compilation in a directory hierarchy that includes directory names with spaces in them. I did this by using "weak quoting" in bash. I also added git submodule initialization and updating so when a user goes to build for MacOS they do not first need to know about git submoduling.
I've added a comment on each line I've changed to help explain. Some of these comments are unnecessary and will probably be removed.
Thanks!
> Allows install paths with spaces on MacOS

- src/tracker/CMakeLists.txt
PS Move API won't work with OpenCV 3, so this makes sure to build with
the correct version.
> Require OpenCV 2.x in CMake

- include/psmove.h
- src/platform/psmove_port_windows.c
- src/psmove.c
- src/psmove_calibration.c
- src/psmove_orientation.cpp
- src/psmove_private.h
This is basically #372 with some code-cleanups for merge.
> Finishing up support the the ZCM2 PSMove controller (with code cleanups)

- include/psmove.h
- src/platform/psmove_port_windows.c
- src/psmove.c
- src/psmove_calibration.c
- src/psmove_orientation.cpp
- src/psmove_private.h
I've been working with @nitsch to get the new ZCM2 PSMoveController working in PSMoveService. I wanted to port the relevant subset of that work over to psmoveapi. Specifically the controller calibration parsing, input packet parsing, and controller pairing in Windows. I've done some preliminary testing on Windows to verify controller pairing and verifying that the orientation work in the test_opengl programs and also updated the calibration dumping code to show ZCM2 calibration fields we are currently interpreting. Given that this is a big enough change I would love any feedback on the implementation. 
The single biggest question I have is if you are ok with the PSMove_Data_Input getting turned into a union of two structs (PSMove_ZCM1_Data_Input and PSMove_ZCM1_Data_Input) or if you would …
> Finishing up support the the ZCM2 PSMove controller

- src/platform/psmove_port_windows.c
Fixes https://github.com/thp/psmoveapi/issues/386 program needs to be run in Administration mode to pair controllers
> updated windows platform file to work on 1903

- src/tracker/platform/camera_control_linux.c
> PSEye on Linux: Fix auto-exposure setting (Fixes #150)

- src/platform/psmove_port_linux.cpp
fix for https://github.com/thp/psmoveapi/issues/400
> don't check for ZCM2 pin on raspberry pi

- src/CMakeLists.txt
- src/tracker/CMakeLists.txt
- src/utils/CMakeLists.txt
- src/utils/libusb.cmake
Hi,
This PR enables sixpair build on Windows.
It
1) downloads dependencies (dirent, libusb, libusbcompat),
2) builds them and
3) links them to psmove target.
The problem is that current code works with libusb driver (from older windows versions or something like that). Libusb can be installed on windows using https://zadig.akeo.ie/
But with it, move controller cannot be used with bluetooth.
Default windows 10 driver is HIDUSB. With it sixpair.c code does not work and I'm not sure if it possible to make it work.
See following links describing the problem:
https://wiibrew.org/wiki/Sixaxis
> However, the SIXAXIS will not transmit any data until a special HID feature report is read, but Windows HID functions do not allow that feature report to be read due to the incorrect HID descriptor.
Also …
> Enable sixpair on Windows.

- examples/c/example.c
- include/psmove.h
- src/daemon/moved.cpp
- src/daemon/moved_client.cpp
- src/platform/psmove_port_windows.c
- src/psmove.c
- src/psmove_calibration.c
- src/psmove_private.h
- src/psmoveapi.cpp
- src/tracker/camera_control.cpp
- src/tracker/psmove_tracker.c
- src/utils/magnetometer_calibration.c
- src/utils/psmovepair.c
- src/utils/psmoveremotepair.cpp
In order to avoid possible problems with different runtimes, memory allocated by the library and passed to the caller should also be freed by the library, not by the caller. This is currently used mostly for strings such as the controller's BDADDR.
Alternatively, we could require library users to supply (custom) malloc/free for the library to use internally.
> Fix freeing of internally allocated memory

- scripts/build_package.sh
Adds the ZIP file for the processing bindings to the build (requires Java bindings to be built, of course).
> Package processing bindings in release (Fixes #421)

- scripts/build_package.sh
Let's add them again as suggested in #422. It has been disabled in c2382286f266ef43b650128dfa9eff2bf70dd298 for whatever reason.
> macOS: Add tracker libraries to package (Fixes #422)

- src/psmove.c
- src/psmove_private.h
Force the `LC_NUMERIC` locale to be the `C` locale, so that `%f` writes/reads `.` always for floating point (and not `,`). As part of this change, also cleaned up the actual read/write code, as it was _much_ more complicated than necessary.
(Historical tidbit: The original code was written by me nearly 10 years ago, see bde8a6a20431261400a2f55f65243e444c17ca76 - quite silly in retrospect to do it like that when `printf()` and `scanf()` are perfectly capable of writing/reading verbatim characters...)
Not yet handled: Unsure how Win32 handles locales, it definitely doesn't seem to have `uselocale()` / `newlocale()` / `freelocale()` from a quick glance at mingw-w64 headers.
> Make magnetometer calibration independent of locale (Fixes #452)

- CHANGELOG.md
- src/tracker/camera_control.cpp
Would be nice to implement this for macOS and Windows as well, but since we use `PS3EYEDriver` by default there, it's not as urgent.
> Implement psmove_tracker_count_connected() for Linux

- CHANGELOG.md
- include/psmove_tracker.h
- src/tracker/psmove_tracker.cpp
- src/tracker/tracker_helpers.cpp
- src/tracker/tracker_helpers.h
Make it explicit which component ordering is used in the variable names. Work with RGB internally (which already was the case for some parts), convert to/from BGR when dealing with the CV image.
> Tracker: Cleanup RGB vs. BGR (vs. 'BRG') component ordering

- CHANGELOG.md
- src/tracker/camera_control.cpp
- src/tracker/platform/psmove_linuxsupport.c
Had this issue where `/dev/video0` disappeared, and the reconnected PS Eye camera ended up being `/dev/video1`. Fix this by globbing for `/dev/video*` instead of trying index values starting at zero.
Unfortunately, OpenCV still uses `/dev/video<index>` for opening the device, so remap the ID when opening a video capture device using OpenCV.
> Camera device enumeration on Linux when using OpenCV

- CHANGELOG.md
- src/tracker/psmove_tracker.cpp
A kernel with size 5 (0..4) has the center exactly at 2, not 3.
> Fix kernel center of erode/dilate filter

- CHANGELOG.md
- include/psmove_tracker.h
- src/tracker/psmove_tracker.cpp
Also fixed some misleading comments and clarified units (all in milliseconds).
> Append _ms suffix to time-related variables in tracker

- src/psmove.c
Something related to normalizing serial numbers broke this for Linux.
> Fix USB detection

- CHANGELOG.md
- docs/camera.rst
- include/psmove_tracker.h
- src/tracker/camera_control.cpp
- src/tracker/camera_control.h
- src/tracker/camera_control_private.h
- src/tracker/platform/camera_control_linux.cpp
- src/tracker/platform/camera_control_macosx.cpp
- src/tracker/platform/camera_control_win32.cpp
- src/tracker/psmove_tracker.cpp
Tweaked exposure settings for PS4 and PS5 camera, fixed exposure locking for PS3 camera (on Linux). Change default resolution for PS4 and PS5 camera, as the capture resolution seems to affect the exposure behavior. Unify PS3EYEDriver camera setting.
> Cleaned up camera control settings

- CHANGELOG.md
- include/psmove_tracker.h
- src/tracker/camera_control.cpp
- src/tracker/camera_control.h
- src/tracker/camera_control_private.h
- src/tracker/platform/camera_control_linux.cpp
- src/tracker/platform/camera_control_macosx.cpp
- src/tracker/platform/camera_control_win32.cpp
- src/tracker/psmove_tracker.cpp
- src/utils/test_tracker.cpp
Return some metadata about the used camera during tracking, for overlaying on the test tracker app.
> Add psmove_tracker_get_camera_info()

- docs/camera.rst
- src/tracker/CMakeLists.txt
- src/tracker/camera_control_driver_avfoundation.mm
- src/tracker/camera_control_driver_v4l2.cpp
- src/tracker/camera_control_layouts.cpp
- src/tracker/camera_control_layouts.h
- src/tracker/psmove_tracker.cpp
- src/utils/ps4_camera_firmware.cpp
- src/utils/test_camera.cpp
Exposure and mirror setting isn't supported, but camera detection using `AVFoundation` and resolution setting is.
> Implement PS4/PS5 camera capture support on macOS

- CHANGELOG.md
- docs/config.rst
- include/psmove.h
- include/psmove_tracker.h
- src/psmove.c
- src/tracker/CMakeLists.txt
- src/tracker/camera_control.cpp
- src/tracker/psmove_tracker.cpp
- src/tracker/psmove_tracker_hue_calibration.cpp
- src/tracker/psmove_tracker_hue_calibration.h
- src/tracker/tracker_helpers.cpp
- src/tracker/tracker_helpers.h
- src/utils/test_camera.cpp
- src/utils/test_tracker.cpp
- src/utils/tracker_camera_calibration.cpp
The tracker core codebase is quite old, this also tries to refactor parts of it (not all, though).
The new hue-based color calibration is faster and takes the environment into account (hues that appear more in the environment get penalized).
This has been developed over the holidays and refined with different lighting conditions, here's the hue-based color calibration with 4 controllers in low and high exposure modes:
[![Fast Hue Calibration](https://img.youtube.com/vi/ptP_zkRvAlE/0.jpg)](https://www.youtube.com/watch?v=ptP_zkRvAlE)
The blinking color calibration has also been updated to do per-color dimming. The cached color mappings (`colormapping.dat`) didn't work all that well in my tests, so they have been removed. The hue calibration is quite fast to do at every startup (see the …
> Improved color calibration methods (blinking, hue)

- src/tracker/camera_control_driver_avfoundation.mm
This helps with getting the right resolution on a built-in iSight HD camera or similar.
> macOS: Fall back to default camera size if not specified

- src/tracker/camera_control_driver_avfoundation.mm
Explicit exposure control isn't a thing still (it would apparently work with [`setExposureModeCustom(duration:iso:completionHandler:)`](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1624646-setexposuremodecustom) on iOS according to developer docs), but let's at least log all the camera capabilities that work on macOS.
> macOS: Log more camera parameters during camera enumeration

- src/CMakeLists.txt
During psmoveapi build psmove_config.h is generated in ${CMAKE_BINARY_DIR} and is not installed along with other ${PSMOVEAPI_HEADERS}. This leads to compilation errors when something dependent on psmoveapi is built.
> install psmove_config.h to include dir

- docs/pairing.rst
Add a message about working around the recent bluez default configuration change, for https://github.com/thp/psmoveapi/issues/489
> bluez configuration workaround documentation

- src/psmove.c
I don't know if this is necessarily still true with the newer move controllers, but with the older ones I have there is now a very large amount of 'dropped frames' log messages all the time with controllers connected.
Frames were always getting 'dropped' in this way before, but in https://github.com/thp/psmoveapi/commit/c9ee3b01b32f63ad5c5d12a76df7265b480b7523 "New logging macros" this particular log message changed from DEBUG, to WARNING, and is therefore now displayed in a default build of the api
As far as I can tell, the 'frame drops' were not, and are not causing any actual problems using the api, so it seems to me that either DEBUG feels like a more appropriate log level to use, or else it would make sense to do something else to reduce the unhelpfully large amount of spam.
(if this …
> Changed 'Dropped frames' log level back down from WARNING to DEBUG

- .github/workflows/build.yml
- scripts/install_dependencies.sh
Let's just install Sphinx, and let's not worry about creating a special venv for now.
Also, Github uses arm64 runners now.
> Fix macOS CI builds

- examples/c/test_navcon.cpp
This fixes the following build issue with GCC 15
```
/builddir/build/BUILD/psmoveapi-4.0.12_20240424git26e1446-build/psmoveapi-26e1446fc9b5996192a1f406d289e64e4e97a195/examples/c/test_navcon.cpp:48:13: error: ‘strcmp’ was not declared in this scope
48 |         if (strcmp(name, "Sony Navigation Controller") == 0) {
|             ^~~~~~
/builddir/build/BUILD/psmoveapi-4.0.12_20240424git26e1446-build/psmoveapi-26e1446fc9b5996192a1f406d289e64e4e97a195/examples/c/test_navcon.cpp:40:1: note: ‘strcmp’ is defined in header ‘<cstring>’; this is probably fixable by adding ‘#include <cstring>’
39 | #include "psmove.h"
+++ |+#include <cstring>
40 |
```
> Add missing include

- src/daemon/moved.cpp
- src/daemon/moved_monitor.h
- src/daemon/moved_monitor_linux.c
- src/daemon/moved_monitor_osx.mm
- src/psmoveapi.cpp
- src/utils/psmovepair.c
Split `EVENT_DEVICE_ADDED` into `EVENT_ZCM1_ADDED` and `EVENT_ZCM2_ADDED` so the proper product ID can be used, this removes two FIXMEs and makes it work on Linux (NOT tested on OSX/windows, no code changes were needed on windows, and the OSX code changes were relatively simple)
> Fix the EventReceiver API (on Linux)
