src/utils/magnetometer_calibration.c

The magnetometer_calibration app used a constant to determine when it had collected a sufficiently wide range of data. This caused problems for myself, depending on location, for others in issue #76, and some others that use my UE4 plugin. The proposed changes now make it so that the constant is used only to update the LED and it is up to the user to end calibration by pressing the MOVE button.

magnetometer_calibration now asks the user to press the MOVE button to stop collecting data

---

src/CMakeLists.txt

Fixed couple of issues with installation:
1) Removed INSTALL and LAYOUT from install command
2) Including tracker and utils subdirs before the first install command, otherwise none of their binaries get installed

Installation fixes

---

include/psmove_tracker.h
src/tracker/psmove_tracker.c

Revert "Remove intrinsics.xml/distortion.xml from settings"

---

src/daemon/moved_client.c
src/utils/moved.c

Some fixes to get moved.exe working on windows.

Moved windows

---

contrib/build_scripts/osx/build-osx-snapshot
src/CMakeLists.txt
src/tracker/CMakeLists.txt

For me, this fixes OS X builds mentioned here (using the build script from contrib): https://github.com/thp/psmoveapi/issues/204

Mac OS X El Capitan build fixes

---

src/psmove.c

This fixes two issues, actually:
- On macOS, sometimes opening controllers fails; this happened because for every connect, the controllers are newly enumerated, and might be enumerated in different order
- With this change, a given fixed set of controllers always has the same ordering, even between starts and independent of the connection ordering, due to the list being sorted by serial number

Sort list of connected controllers

---

docs/build.rst

A couple more dependencies for the clean Homebrew installation.

Updates build instructions for macOS Sierra

---

.appveyor.yml
.travis.yml
bindings/python/psmoveapi.py
contrib/build_scripts/msvc/build_msvc_common.bat
contrib/build_scripts/msvc/package.sh
contrib/build_scripts/osx/build-osx-snapshot
src/CMakeLists.txt

WIP; automatic upload to Github releases.

Releases deployment

---

src/psmove.c

This happens on Pocket C.H.I.P and Linux-on-ARM.

Work around hid_write() == 0 on Linux

---

src/platform/psmove_port_linux.c

Ideally we can determine through some other means whether Bluetooth is running or not, but this works for now and improves the current situation.

Linux: Try to restart Bluetooth if address cannot be determined

---

src/platform/psmove_port_windows.c
src/tracker/platform/camera_control_macosx.c
src/tracker/platform/camera_control_win32.c

Just a little bit of cleaning up on Windows and OSX.

Fix warnings

---

.appveyor.yml
bindings/python/psmoveapi.py
docs/build.rst
scripts/build_package.sh
scripts/visualc/build_msvc.bat

This makes it possible to run applications using the new Python bindings on Windows. It might also help with https://github.com/adangert/JoustMania/issues/67.

Windows 32-bit builds using Visual C++ and Python bindings fix

---

bindings/unity/README
bindings/unity/src/MoveController.cs
bindings/unity/src/UniMoveController.cs
bindings/unity/src/UniMoveTest.cs

Upstream commit: https://github.com/CopenhagenGameCollective/UniMove/commit/72baf91fef1a1c8623660b97b30359c4af2fcecc

Update UniMove bindings to 72baf91f

---

.appveyor.yml

This should make releasing fully automatic.

AppVeyor: Upload artifacts to GitHub

---

src/daemon/moved.cpp
src/platform/psmove_port_linux.cpp

If multiple host adapters are installed, allow choosing which one to use via environment variables.

Linux: Handle multiple host adapters

---

examples/python/ep_whack.py

The file is not compatible with Python 3 as it appears. This minor update should make it compatible.

Updated the file to be Python 3 compatible

---

.travis.yml

Seems like the problem solved itself by upgrading to a newer Xcode version.

Use newer macOS image (Fixes #430)

---

scripts/visualc/build_msvc.bat

The libusb patches still need to be updated, external cloning has been updated in https://github.com/thp/psmoveapi/commit/8caf07acd9d03affc066e314f762df08f070cfb8

Update Windows script where possible

---

scripts/linux/build-debian

Linux/Debian: Force building tracker (Fixes #437)

---

CMakeLists.txt
cmake/common.cmake
include/psmove.h
src/daemon/moved_monitor_linux.c
src/platform/psmove_port_linux.cpp
src/platform/psmove_port_windows.c
src/psmove.c
src/psmove_calibration.c
src/psmove_private.h
src/tracker/psmove_tracker.cpp

Catch some obvious compiler warnings.

Enable -Wextra and -Werror, also for C

---

CHANGELOG.md
examples/labs/accelerometer3d/orientation.h
examples/labs/movetytouch/movetytouch.h
examples/labs/orientation/orientation.h
include/psmove.h
include/psmove_tracker.h
src/daemon/moved.cpp
src/platform/psmove_port_linux.cpp
src/platform/psmove_port_osx.mm
src/platform/psmove_port_windows.c
src/psmove.c
src/psmove_port.h
src/psmove_private.h
src/tracker/camera_control.cpp
src/tracker/camera_control.h
src/tracker/camera_control_private.h
src/tracker/psmove_tracker.cpp
src/utils/test_camera.cpp
src/utils/test_extension.c
src/utils/test_responsiveness.c
src/utils/test_tracker.cpp

C99 stdbool was (obviously) already a thing in 2011, so could have used that from the start...

Use C99/C++ bool type instead of custom enum

---

CHANGELOG.md
include/psmove_tracker.h
src/tracker/camera_control.cpp
src/tracker/camera_control.h
src/tracker/camera_control_driver.cpp
src/tracker/camera_control_driver.h
src/tracker/psmove_tracker.cpp
src/utils/distance_calibration.cpp
src/utils/psmovecli.cpp
src/utils/tracker_camera_calibration.cpp

The calibration file format has changed slightly. There's now a separate tool to verify the calibration.

Port camera and distance calibration to OpenCV 4

---

cmake/common.cmake
scripts/build_package.sh
scripts/visualc/build_msvc.bat
src/psmove_format.h
src/utils/ps4_camera_firmware.cpp

Actually build the tracker and fix compiler issues due to MSVC shortcomings.

Fix Win32 build and MSVC pecularities

---

.readthedocs.yaml

Builds broke: https://readthedocs.org/projects/psmoveapi/builds/24174695/
This should fix it.

Add Read the Docs configuration
